#ifndef __PHWIOSCOPEIOCTLCODE_H__
#define __PHWIOSCOPEIOCTLCODE_H__

#define IOCTL_START_APP \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4001, METHOD_BUFFERED, FILE_ANY_ACCESS)
    
#define IOCTL_CLOSE_APP \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4002, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_CAPTURE_RUN \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4003, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_CAPTURE_PAUSE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4004, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_REQ_PKT \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4005, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_ON_CAP_SPECIFIC_DEV \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4006, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_OFF_CAP_SPECIFIC_DEV \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4007, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GET_CAPTURE_MODE_ACTIVATED_DEV_PDONAME \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4008, METHOD_BUFFERED, FILE_ANY_ACCESS)


#endif
